Hey, I added a feature to support tmux's clipboard sharing for the Xorg version of st, and I also ported it to wayland.
michaelforney/st pull request #7
Opened 2017-01-18 23:21 UTC by fpqc

Hiya, great job with the wayland ver of st.  I ported over some new functionality to your Wayland version!

2017-01-19 07:33 UTC, michaelforney commented
Thanks. I'll apply it if it is accepted in upstream st. Until then, I am happy to push it to a separate branch.

2017-01-19 07:38 UTC, michaelforney requested changes
Some minor stylistic issues that conflict with the style throughout the rest of the file.

2017-01-19 07:38 UTC, michaelforney commented on st.c
> +	uint32_t globalserial; /*global event serial*/
Add spaces between `*` and comment.

2017-01-19 07:38 UTC, michaelforney commented on st.c
> +				char *src=strescseq.args[2];
Spaces around `=`.

2017-01-19 07:38 UTC, michaelforney commented on st.c
> +				char *buf=xmalloc(l+1);
Spaces around `=`.

2017-01-19 07:38 UTC, michaelforney commented on st.c
> +			if (narg > 2){
Space between `)` and `{`.

2017-01-19 07:38 UTC, michaelforney commented on st.c
> +		wl.globalserial=serial;
Spaces around `=`.

2017-01-19 07:38 UTC, michaelforney commented on st.c
> +			wl.globalserial=serial;
Spaces around `=`.

2017-01-19 08:05 UTC, fpqc commented
Fixed.  This is the first PR I've ever submitted on github, so I don't know if I need to comment for you to get the notif.

2017-01-20 18:42 UTC, michaelforney commented on st.c
> +		wl.globalserial = serial;
Shouldn't the serial be saved on key press, not key release?

The key press is the action that is likely to trigger tmux to send the set selection escape sequence, right?

2017-01-20 19:03 UTC, fpqc commented
@michaelforney I figured doing it on key release would avoid a race condition, but I don't know.  I asked in #wayland on IRC and they seemed to think doing it on key release should be fine.  I can change it if you want.

2017-01-21 20:01 UTC, michaelforney commented
I think it needs to be done on key press because that is when tmux might trigger the copy action. If you do it on key release, the copy may not work if another application set the selection between the time the previous key was released and the time the current key was pressed.

I'm not too familiar with tmux and mouse bindings. When would a button cause a selcopy?

2017-01-21 20:22 UTC, fpqc commented
@michaelforney There is a keyboard select mode by using (in vi-style keybindings) 

ctrl+b [ (enter select mode)
arrow keys to move caret
space starts the selection
arrow keys to select text
enter completes the selection

2017-01-21 21:52 UTC, michaelforney commented on st.c
> +		return;
Umm... you do realize that state is either pressed or released, and if you return early on both, the rest of the function won't run, right?

Anyway, I'll just squash your commits together and fix up some minor things so we don't have to continue this back and forth.

2017-01-21 22:49 UTC, fpqc commented
Sorry, wasn't paying attention. I did the commit from my phone.

2017-01-21 23:18 UTC, michaelforney commented
Pushed to selection branch.

2017-01-21 23:18 UTC, closed without merging